### ISSUE TITLE
Matomo 5 compatibility

### ISSUE THREAD

**Issue by snake14** [MichaelHeerklotz/plugin-DeviceNetworkInformation#3]
Dear Matomo Plugin Author,
We are excited that Matomo 5.0.0 is on the horizon, and we would greatly appreciate your assistance in ensuring that your plugin remains compatible with this upcoming release. Maintaining compatibility will enable Matomo users to seamlessly use your plugin after they upgrade to Matomo 5. (If the plugin is not updated to be compatible with Matomo 5, then whenever a user will upgrade to Matomo 5, the plugin would be automatically disabled to prevent issues.)

Updating your plugin to be Matomo 5 compatible is a straightforward process and should not require a significant time investment. You can find more information about updating your plugin at: https://developer.matomo.org/guides/migrate-matomo-4-to-5

Thank you for your ongoing support and commitment to the Matomo community. 
Your contribution is really appreciated!

The Matomo Team

PS: we’re also available to help if you have any question about making the plugin compatible.

**Comment by snake14** [comment]
Hi @MichaelRoosz . Just a reminder that the Matomo 5 release is fast approaching. Please let me know if you have any questions about making your plugin Matomo 5 compatible.

**Comment by MichaelRoosz** [comment]
Thank you, I have updated the plugin for Matomo 5.
